import {
  Award,
  BadgeCheck,
  BatteryCharging,
  Building2,
  CalendarClock,
  ClipboardCheck,
  Clock,
  HeartHandshake,
  House,
  Leaf,
  Lightbulb,
  Network,
  PlugZap,
  Receipt,
  Ruler,
  Send,
  ShieldCheck,
  Siren,
  Sparkles,
  Sun,
  Users,
  Wrench,
  type LucideIcon,
} from 'lucide-react';
import type { IconName } from '@/types';

/** Zentrale Icon-Zuordnung, damit Daten nur serialisierbare Namen enthalten. */
export const icons: Record<IconName, LucideIcon> = {
  PlugZap,
  Building2,
  House,
  Sun,
  BatteryCharging,
  Lightbulb,
  Network,
  Siren,
  Award,
  Clock,
  Receipt,
  CalendarClock,
  BadgeCheck,
  Sparkles,
  Send,
  Users,
  Wrench,
  ClipboardCheck,
  ShieldCheck,
  HeartHandshake,
  Ruler,
  Leaf,
};
